### ISSUE TITLE
License is proprietary - but most of it looks like BSD-3-Clause

### ISSUE THREAD

**Issue by sthagen** [glyn/jsonpath-nondeterminism#3]
I came here from an email of yours to the IETF jsonpath mailing list advertising the repository.

So, from the side lines - hopefully welcome feedback and not perceived as intrusive - a comment on the license:

I noticed the license was not detected as per an SPDX code and reading the license confused me.

Most of the license looks like BSD-3-Clause, but with four modifications:

1. All rights reserved. &rightarrow; proprietary, non-sharing?
2. Unordered list instead of the ordered list (cf. <https://opensource.org/license/bsd-3-clause> or <https://spdx.org/licenses/BSD-3-Clause.html>) &rightarrow; no-impact on license 
3. In the third list item `copyright holder` has been replaced with the name of the copyright holder &rightarrow; no impact on license, but will trigger detection problems (as with GitHub not detecting BSD-3-Clause)
4. The second sentence in the final "all uppercase" paragraph the term `COPYRIGHT HOLDER` has been replaced with `COPYRIGHT OWNER`. &rightarrow; I am no lawyer, but the introduction of such a variation (holder to owner) does not help assessing compliance when sharing.

So, in case this is the license you want, all is good, and please close this issue as resolved.

In case the BSD-3-Clause license was intended, I suggest to instead use the following text:

```
BSD 3-Clause License

Copyright (c) 2024, Glyn Normington

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by glyn** [comment]
I used the Haskell stack tool to generate this project, including its LICENSE. But I agree that the BSD 3-clause license would be a better choice, thanks. Fixed in e0970c0218cb09e122574699f55f54f2cc8dfbd4.

**Comment by glyn** [comment]
Started a [discussion](https://discourse.haskell.org/t/non-standard-license-generated-by-stack-new/9059) about this on the Haskell Discourse.

**Comment by sthagen** [comment]
@glyn thanks a lot and your initiative already nicely teleported the information into places close to fixes: https://github.com/haskell/cabal/issues/9812

**Comment by glyn** [comment]
@sthagen Looks like the stack templates are being fixed (which is what I used), as well as `cabal init`. (Discourse didn't notify me of any updates, so this is all a very pleasant outcome.)

**Comment by glyn** [comment]
@sthagen I doubled back and checked. The Haskell stack tool has been updated and now generates the correct BSD license.

**Comment by sthagen** [comment]
@glyn thanks a lot for propagating the change into the wider ecosystem and following up. Much appreciated!
