### ISSUE TITLE
Descending into array elements

### ISSUE THREAD

**Issue by jg-rp** [glyn/jsonpath-nondeterminism#4]
Hi @glyn,

I've been trying to get a simulation of JSONPath nondeterminism to produce results matching yours and I'm getting hung up on a possible conflict between two examples. 

Specifically, given the explosive example, section [section 2.5.2.3](https://www.rfc-editor.org/rfc/rfc9535#name-examples-9) says "`{"k": 6}` must appear before `4`..". Suggesting that all elements from `[{'j': 4}, {'k': 6}]` must be visited before descending into `{'j': 4}` and `{'k': 6}`. I also note that this rule precludes the use of a depth-first, pre-order traversal of the node tree, as that would have `4` appearing before `{"k": 6}`.

A tree view of the explosive example, for reference:

```plain
{'a': [5, 3, [{'j': 4}, {'k': 6}]], 'o': {'j': 1, 'k': 2}}
├── [5, 3, [{'j': 4}, {'k': 6}]]
│   ├── 5
│   ├── 3
│   └── [{'j': 4}, {'k': 6}]
│       ├── {'j': 4}
│       │   └── 4
│       └── {'k': 6}
│           └── 6
└── {'j': 1, 'k': 2}
    ├── 1
    └── 2
```

If I apply the same approach to your "interesting example", that is, always visiting array elements before their children, I only get one ordering (before applying the wildcard selector), which does not match your results or my previous attempts at simulating nondeterminism.

```plain
[[[1]], [2]], [[1]], [2], [1], 1, 2
```

A tree view of the interesting example, for reference:

```plain
[[[1]], [2]]
├── [[1]]
│   └── [1]
│       └── 1
└── [2]
    └── 2
```

This has been driving me nuts since your CTS pull request last week. I am able to change the simulation to match one example or the other, but never both.

**Comment by glyn** [comment]
Hi @jg-rp 

Let's go through the explosive example in more detail. My simulator produces the following possible nodelists:
```
[{"j":1,"k":2},[5,3,[{"j":4},{"k":6}]],1,2,5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,6]
[{"j":1,"k":2},[5,3,[{"j":4},{"k":6}]],2,1,5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,6]
[{"j":1,"k":2},[5,3,[{"j":4},{"k":6}]],5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},1,2,4,6]
[{"j":1,"k":2},[5,3,[{"j":4},{"k":6}]],5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},2,1,4,6]
[{"j":1,"k":2},[5,3,[{"j":4},{"k":6}]],5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,1,2,6]
[{"j":1,"k":2},[5,3,[{"j":4},{"k":6}]],5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,2,1,6]
[{"j":1,"k":2},[5,3,[{"j":4},{"k":6}]],5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,6,1,2]
[{"j":1,"k":2},[5,3,[{"j":4},{"k":6}]],5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,6,2,1]
[{"j":1,"k":2},[5,3,[{"j":4},{"k":6}]],5,3,[{"j":4},{"k":6}],1,2,{"j":4},{"k":6},4,6]
[{"j":1,"k":2},[5,3,[{"j":4},{"k":6}]],5,3,[{"j":4},{"k":6}],2,1,{"j":4},{"k":6},4,6]
[[5,3,[{"j":4},{"k":6}]],{"j":1,"k":2},1,2,5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,6]
[[5,3,[{"j":4},{"k":6}]],{"j":1,"k":2},2,1,5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,6]
[[5,3,[{"j":4},{"k":6}]],{"j":1,"k":2},5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},1,2,4,6]
[[5,3,[{"j":4},{"k":6}]],{"j":1,"k":2},5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},2,1,4,6]
[[5,3,[{"j":4},{"k":6}]],{"j":1,"k":2},5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,1,2,6]
[[5,3,[{"j":4},{"k":6}]],{"j":1,"k":2},5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,2,1,6]
[[5,3,[{"j":4},{"k":6}]],{"j":1,"k":2},5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,6,1,2]
[[5,3,[{"j":4},{"k":6}]],{"j":1,"k":2},5,3,[{"j":4},{"k":6}],{"j":4},{"k":6},4,6,2,1]
[[5,3,[{"j":4},{"k":6}]],{"j":1,"k":2},5,3,[{"j":4},{"k":6}],1,2,{"j":4},{"k":6},4,6]
[[5,3,[{"j":4},{"k":6}]],{"j":1,"k":2},5,3,[{"j":4},{"k":6}],2,1,{"j":4},{"k":6},4,6]
```

This agrees with the spec in that `{k:6}` always appears before `4`. Let me try to explain why.

It's sufficient to consider `$..[*]` applied to `[{"j": 4}, {"k": 6}]`. As you point out, the tree form of this is:
```
 [{"j": 4}, {"k": 6}]
 ├── {"j": 4}
 │   └── 4
 └── {"k": 6}
     └── 6
```

The spec requires that array elements are visited in order so `{"j": 4}` must be visited before `{"k": 6}`.

The spec also requires that parents are visited before their children, so:
* `[{"j": 4}, {"k": 6}]` is visited before `{"j": 4}` and `{"k": 6}`
* `{"j": 4}` is visited before 4
* `{"k": 6}` is visited before 6

But the step I think you are missing is that the child segment `[*]` needs to be applied to all the visited nodes. Let's see what happens to each node (regardless of the order in which the nodes are visited!) when [*] is applied:

* `[{"j": 4}, {"k": 6}]` produces the nodelist `{"j": 4}`, `{"k": 6}` (I'm not writing this as a JSON array to avoid confusion)
* `{"j": 4}` produces the nodelist `4`
* `4` produces the empty nodelist
* `{"k": 6}` produces the nodelist `6`
* `6` produces the empty nodelist

So, for any valid traversal order of the descendants, `$..[*]` applied to ` [{"j": 4}, {"k": 6}]` produces the nodelist:
* `{"j": 4}`, `{"k": 6}`, 4, 6

So, before we go any further, do you follow the reasoning here? (And did you read "Confession" in my post?)

**Comment by jg-rp** [comment]
> do you follow the reasoning here?

I'm with you so far. And thank you for taking the time to walk through this with me.

> And did you read "Confession" in my post?

I've read it again and, although the effect of the wildcard selector on nodes with primitive values is (I thought) reasonably intuitive to me, I think my interpretation of "`{"k": 6}` must appear before `4`" is related, and is ultimately where my mistake lies. I've been thinking of that statement as describing the order of visitation **before** applying the wild card selector, when in fact it is describing the order of results for the query in its entirety.

**Comment by jg-rp** [comment]
Results from my [latest attempt](https://github.com/jg-rp/python-jsonpath-rfc9535/pull/2) match your result for all examples.

Thanks again, @glyn.

**Comment by glyn** [comment]
@jg-rp Glad it worked out James. It's a tricky area of the spec and I should probably devote a blog post to it.

Don't hesitate if you have further questions.
